import { CSSProperties } from "react";
import { colors } from "./colors";

export const styles: Record<string, CSSProperties> = {
  header: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "16px 24px",
    background: "#fff",
    borderBottom: "1px solid #e0e0e0",
  },
  backBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    padding: 0,
  },
  title: {
    margin: 0,
    fontSize: 18,
    fontWeight: 600,
    color: "#1a1a1a",
  },
page: {
  minHeight: "100vh",
  background: colors.lightTeal,
  padding: "16px",     
  display: "flex",
  flexDirection: "column",
  gap: 16,               
},
  card: {
    background: colors.white,
    borderRadius: 16,
    padding: "20px",
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: colors.black,
    marginBottom: 16,
    margin: "0 0 16px 0",
  },
  radioRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 0",
    borderBottom: "1px solid #f0f0f0",
    cursor: "pointer",
  },
  radioLabel: {
    fontSize: 15,
    color: colors.black,
  },
  saveBtn: {
  width: "100%",
  padding: "16px",
  borderRadius: 12,
  border: "none",
  background: colors.darkTeal,
  color: colors.white,
  fontSize: 16,
  fontWeight: 600,
  cursor: "pointer",
},
avatarWrapper: {
  position: "relative" as const,
  width: 100,
  height: 100,
  margin: "0 auto",
},
avatarCircle: {
  width: 100,
  height: 100,
  borderRadius: "50%",
  border: colors.tealPrimary + " 3px solid",
  overflow: "hidden",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  background: colors.white,
},
avatarImg: {
  width: "100%",
  height: "100%",
  objectFit: "cover" as const,
},
avatarInitials: {
  fontSize: 60,
},
cameraBtn: {
  position: "absolute" as const,
  bottom: 2,
  right: 2,
  width: 32,
  height: 32,
  borderRadius: "50%",
  background: colors.lightTeal,
  border: colors.tealPrimary + " 2px solid",
  cursor: "pointer",
  fontSize: 18,
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
},
label: {
  fontSize: 13,
  fontWeight: 500,
  color: colors.grayText,
  marginBottom: 6,
  marginTop: 12,
  display: "block",
},
input: {
  width: "100%",
  padding: "12px 14px",
  borderRadius: 10,
  border: "1px solid #e0e0e0",
  fontSize: 15,
  color: colors.black,
  background: colors.white,
  boxSizing: "border-box" as const,
  outline: "none",
},
chatBtn: {
  width: "100%",
  padding: "16px",
  borderRadius: 12,
  border: "2px solid #54A096",
  background: colors.white,
  color: colors.tealPrimary,
  fontSize: 16,
  fontWeight: 600,
  cursor: "pointer",
  marginTop: 12,
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  gap: 8,
},
saveToast: {
  position: "fixed",
  bottom: "24px",
  right: "24px",
  backgroundColor: colors.white,
  color: colors.black,
  padding: "20px 24px",
  borderRadius: 16,
  boxShadow: "0 8px 24px rgba(0, 0, 0, 0.12)",
  display: "flex",
  alignItems: "center",
  gap: "12px",
  zIndex: 9999,
  minWidth: "320px",
},

saveToastIcon: {
  fontSize: 24,
  color: colors.black,
  flexShrink: 0,
},
saveToastText: {
  fontSize: 16,
  fontWeight: 500,
},

};

export const iconProps = {
  backIcon: {
    size: 24,
    color: colors.grayText,
  },
};
