import { CSSProperties } from "react";
import { colors } from "./colors";
import { TbFridgeOff } from "react-icons/tb";


export const styles: Record<string, CSSProperties> = {
  header: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "16px 24px",
    background:colors.white,
    borderBottom: `1px solid ${colors.bordwhite}`,
  },
  backBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    padding: 0,
  },
  title: {
    margin: 0,
    fontSize: 18,
    fontWeight: 600,
    color: colors.black,
  },
page: {
  minHeight: "100vh",
  background: colors.lightTeal,
  padding: "16px",     
  display: "flex",
  flexDirection: "column",
  gap: 16,               
},
  card: {
    background: colors.white,
    width: "70%",
    borderRadius: 16,
    padding: "21px",
    margin: "0 auto 24px auto",
    marginBottom: 10,
  },
cardText: {
  fontSize: 15,
  fontWeight: 400,
  color: colors.black,
  marginTop: 10, 
  marginBottom: 16,
  marginLeft: 0,
  marginRight: 0,
  display: "block",
},
menuRow: {
  display: "flex",
  alignItems: "center",
  gap: 10,
  padding: "14px 0",
  borderBottom: `1px solid ${colors.bordwhite}`,
  cursor: "pointer",
},
menuRowText: {
  fontSize: 18,
  fontWeight: 600,
  color: colors.black,
},
subText: {
  textAlign: "center",
  fontSize: 16,
  margin: "18px",
  fontWeight: 400,
  color: colors.grayText,
  marginTop: 4,
},
greenCard: {
  background: colors.lightTeal,
  borderRadius: 16,
  padding: 16,
  marginTop: 12,
},
greenCardHeader: {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "flex-start",
  marginBottom: 12,
},
greenCardLabel: {
  fontSize: 15,
  color: colors.grayText,
  marginBottom: 4,
},
greenCardTitle: {
  fontSize: 18,
  fontWeight: 700,
  color: colors.black,
},
membersText: {
  fontSize: 15,
  color: colors.grayText,
},
scannerBtn: {
  width: "60%",
  padding: "10px",
  margin: "16px auto 0 auto",
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  gap: "10px",
  borderRadius: 12,
  border: "none",
  backgroundColor: colors.buttons,
  color: colors.white,
  fontSize: 16,
  fontWeight: 600,
  cursor: "pointer",
},
inviteBox: {
  background: colors.white,
  borderRadius: 12,
  padding: "12px 16px",
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  marginBottom: 12,
},
inviteLabel: {
  fontSize: 12,
  color: colors.grayText,
  marginBottom: 4,
},
inviteCode: {
  fontSize: 15,
  fontWeight: 700,
  color: colors.darkTeal,
},
copyBtn: {
  background: colors.buttons,
  color: colors.white,
  border: "none",
  borderRadius: 10,
  padding: "8px 16px",
  cursor: "pointer",
  fontSize: 14,
  fontWeight: 600,
},
memberRow: {
  background: colors.white,
  borderRadius: 12,
  padding: "10px 14px",
  display: "flex",
  alignItems: "center",
  gap: 12,
  marginBottom: 8,
},

memberAvatar: {
  width: 40,
  height: 40,
  borderRadius: "50%",
  background: colors.lightTeal,
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  fontSize: 16,
  fontWeight: 600,
  color: colors.darkTeal,
},
memberName: {
  fontSize: 15,
  fontWeight: 600,
  color: colors.black,
},
leaveBtn: {
  width: "60%",
  padding: "10px",
  margin: "16px auto 0 auto",
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  gap: "10px",
  borderRadius: 12,
 border: `1px solid ${colors.errorRed}`,
  backgroundColor: colors.white,
  color: colors.errorRed,
  fontSize: 16,
  fontWeight: 600,
  cursor: "pointer",
},
copyToast: {
  position: "fixed",
  bottom: "24px",
  right: "24px",
  backgroundColor: colors.white,
  color: colors.black,
  padding: "20px 24px",
  borderRadius: 16,
  boxShadow: "0 8px 24px rgba(0, 0, 0, 0.12)",
  display: "flex",
  alignItems: "center",
  gap: "12px",
  zIndex: 9999,
  minWidth: "320px",
},

copyToastIcon: {
  fontSize: 24,
  color: colors.black,
  flexShrink: 0,
},

copyToastText: {
  fontSize: 16,
  fontWeight: 500,
},
createBtn: {
  width: "60%",
  padding: "10px",
  margin: "24px auto 0 auto",
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  gap: "10px",
  borderRadius: 12,
  background: colors.buttons,
  color: colors.white,
  fontSize: 16,
  fontWeight: 600,
  cursor: "pointer",
},
joinBtn: {
  width: "60%",
  padding: "10px",
  margin: "24px auto 0 auto",
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  gap: "10px",
  borderRadius: 12,
  border: `2px solid ${colors.buttons}`,
  background: colors.white,
  color: colors.buttons,
  fontSize: 16,
  fontWeight: 600,
  cursor: "pointer",
},
input: {
  width: "60%",
  padding: "10px",
  margin: "16px auto 0 auto",
    display: "flex",
  justifyContent: "center",
  alignItems: "center",
  gap: "10px",
  border: "1px solid #ccc",
  borderRadius: "10px",
  fontSize: "14px",
  backgroundColor: "colors.white",
  boxSizing: "border-box",
  marginBottom: "12px",
},
imageWrapper: {
  position: 'relative' as const,
},
imagePreview: {
  width: 80,
  height: 80,
  borderRadius: 8,
  objectFit: 'cover' as const,
},
imageDeleteBtn: {
  position: 'absolute' as const,
  top: -6,
  right: -6,
  width: 20,
  height: 20,
  borderRadius: '50%',
  background: colors.white,
  color: colors.black,
  border: '1px solid #e0e0e0',
  cursor: 'pointer',
  fontSize: 12,
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
},
imagesContainer: {
  display: 'flex',
  gap: 8,
  marginTop: 12,
  flexWrap: 'wrap' as const,
  alignItems: 'center',
  justifyContent: 'center',
},
sendScanBtn: {
  width: 50,
  height: 50,
  borderRadius: '50%',
  background: colors.buttons,
  color: colors.white,
  border: 'none',
  cursor: 'pointer',
  fontSize: 28,
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
},
};

export const iconProps = {
  backIcon: {
    size: 24,
    color: colors.grayText,
  },
  peopleIcon: {
    size: 20,
    color: colors.buttons,
  },
  cameraIcon: {
    size: 17,
    color: colors.buttons,
  },
  uploadIcon: {
    size: 17,
    color: colors.white,
  },
  copyIcon: {
    size: 14,
    color: colors.darkTeal,
  },
  leaveIcon: {
    size: 17,
    color: colors.errorRed,
  },
  fridgeOffIcon: {
    size: 20,
    color: colors.black,
  },
  sendIcon: {
  size: 24,
  color: colors.white,
},

};