import { CSSProperties } from "react";
import { colors } from "./colors";
import { TbFridgeOff } from "react-icons/tb";


export const styles: Record<string, CSSProperties> = {
  header: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "16px 24px",
    background:colors.white,
    borderBottom: `1px solid ${colors.bordwhite}`,
  },
  backBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    padding: 0,
  },
  title: {
    margin: 0,
    fontSize: 18,
    fontWeight: 600,
    color: colors.black,
  },
page: {
  minHeight: "100vh",
  background: colors.lightTeal,
  padding: "16px",     
  display: "flex",
  flexDirection: "column",
  gap: 16,               
},
  card: {
    background: colors.white,
    borderRadius: 16,
    padding: "20px 24px",
    border: `1px solid ${colors.bordwhite}`,
    display: "flex",
    flexDirection: "column" as const,
  },
cardText: {
  fontSize: 14,
  fontWeight: 400,
  color: colors.grayText,
  marginTop: 14,
  marginBottom: 18,
  marginLeft: 0,
  marginRight: 0,
  display: "block",
  lineHeight: 1.5,
},
cardsContainer: {
  display: "grid",
  gridTemplateColumns: "1fr 1fr",
  gap: 16,
  width: "100%",
  maxWidth: 1400,
  margin: "0 auto",
},
singleCardContainer: {
  display: "flex",
  justifyContent: "center",
},
menuRow: {
  display: "flex",
  alignItems: "center",
  gap: 10,
  paddingBottom: 14,
  borderBottom: `1px solid ${colors.bordwhite}`,
},
menuRowText: {
  fontSize: 17,
  fontWeight: 700,
  color: colors.black,
  letterSpacing: -0.1,
},
subText: {
  textAlign: "center",
  fontSize: 16,
  margin: "18px",
  fontWeight: 400,
  color: colors.grayText,
  marginTop: 4,
},
greenCard: {
  background: colors.lightTeal,
  borderRadius: 14,
  padding: 18,
  marginTop: 16,
},
greenCardHeader: {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  marginBottom: 14,
  gap: 12,
  flexWrap: "wrap" as const,
},
greenCardHeaderLeft: {
  display: "flex",
  flexDirection: "column" as const,
  gap: 2,
  minWidth: 0,
},
greenCardLabel: {
  fontSize: 11,
  fontWeight: 700,
  color: colors.grayText,
  margin: 0,
  textTransform: "uppercase" as const,
  letterSpacing: 0.6,
},
greenCardTitle: {
  fontSize: 20,
  fontWeight: 700,
  color: colors.darkTeal,
  margin: 0,
  lineHeight: 1.2,
  textTransform: "capitalize" as const,
},
membersBadge: {
  display: "inline-flex",
  alignItems: "center",
  gap: 6,
  background: colors.white,
  color: colors.darkTeal,
  fontSize: 12,
  fontWeight: 700,
  padding: "5px 12px",
  borderRadius: 999,
  textTransform: "uppercase" as const,
  letterSpacing: 0.4,
  boxShadow: "0 1px 2px rgba(0, 0, 0, 0.04)",
  whiteSpace: "nowrap" as const,
},
scannerBody: {
  display: "flex",
  flexDirection: "column" as const,
  flex: 1,
  minHeight: 0,
},
// Large, tappable drop-zone that fills the card. Replaces the tiny pill
// button with a proper upload affordance — bigger target, more discoverable,
// visually balances the greenCard in the Shared Fridge card.
dropZone: {
  flex: 1,
  minHeight: 180,
  marginTop: 4,
  border: `2px dashed ${colors.accentGreen}`,
  borderRadius: 14,
  background: colors.lightTeal,
  display: "flex",
  flexDirection: "column" as const,
  alignItems: "center",
  justifyContent: "center",
  gap: 10,
  padding: "20px 16px",
  cursor: "pointer",
  textAlign: "center" as const,
  transition: "background 0.15s ease",
},
dropZoneIconWrap: {
  width: 56,
  height: 56,
  borderRadius: "50%",
  background: colors.white,
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  boxShadow: "0 2px 6px rgba(0, 188, 144, 0.18)",
},
dropZoneTitle: {
  fontSize: 15,
  fontWeight: 700,
  color: colors.darkTeal,
  margin: 0,
},
dropZoneHint: {
  fontSize: 12,
  color: colors.grayText,
  margin: 0,
},
scannerSubtitle: {
  fontSize: 13,
  color: colors.grayText,
  marginTop: 10,
  marginBottom: 4,
  lineHeight: 1.5,
},
// Still used for the body card of the No Fridge Yet state.
scannerBtn: {
  width: "100%",
  padding: "14px 16px",
  marginTop: 4,
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  gap: 10,
  borderRadius: 12,
  border: "none",
  backgroundColor: colors.accentGreen,
  color: colors.white,
  fontSize: 15,
  fontWeight: 600,
  cursor: "pointer",
  boxShadow: "0 2px 6px rgba(0, 188, 144, 0.25)",
},
inviteBox: {
  background: colors.white,
  borderRadius: 12,
  padding: "12px 14px 12px 16px",
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  marginBottom: 14,
  gap: 12,
},
inviteLabel: {
  fontSize: 11,
  fontWeight: 700,
  color: colors.grayText,
  marginBottom: 2,
  margin: 0,
  textTransform: "uppercase" as const,
  letterSpacing: 0.6,
},
inviteCode: {
  fontSize: 16,
  fontWeight: 700,
  color: colors.darkTeal,
  margin: 0,
  marginTop: 2,
  letterSpacing: 1.5,
  fontFamily:
    'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Monaco, Consolas, monospace',
},
copyBtn: {
  background: colors.accentGreen,
  color: colors.white,
  border: "none",
  borderRadius: 10,
  padding: "8px 14px",
  cursor: "pointer",
  fontSize: 13,
  fontWeight: 600,
  display: "inline-flex",
  alignItems: "center",
  gap: 6,
  whiteSpace: "nowrap" as const,
},
// A subtle "Members" label above the member pills.
sectionLabel: {
  fontSize: 11,
  fontWeight: 700,
  color: colors.grayText,
  marginBottom: 8,
  textTransform: "uppercase" as const,
  letterSpacing: 0.6,
},
memberPillsContainer: {
  display: "flex",
  flexWrap: "wrap" as const,
  gap: 8,
},
memberPill: {
  display: "inline-flex",
  alignItems: "center",
  gap: 10,
  background: colors.white,
  borderRadius: 999,
  padding: "4px 16px 4px 4px",
  boxShadow: "0 1px 2px rgba(0, 0, 0, 0.05)",
  maxWidth: "100%",
},
memberAvatar: {
  width: 32,
  height: 32,
  borderRadius: "50%",
  background: colors.lightTeal,
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  fontSize: 13,
  fontWeight: 700,
  color: colors.darkTeal,
  flexShrink: 0,
  overflow: "hidden" as const,
},
memberName: {
  fontSize: 14,
  fontWeight: 600,
  color: colors.black,
  whiteSpace: "nowrap" as const,
  overflow: "hidden" as const,
  textOverflow: "ellipsis" as const,
  maxWidth: 200,
},
memberNameMe: {
  color: colors.grayText,
  fontWeight: 500,
  marginLeft: 4,
},
leaveBtnWrap: {
  display: "flex",
  justifyContent: "flex-end",
  marginTop: 16,
},
leaveBtn: {
  display: "inline-flex",
  alignItems: "center",
  gap: 8,
  padding: "8px 16px",
  borderRadius: 10,
  border: `1px solid ${colors.errorRed}`,
  backgroundColor: colors.white,
  color: colors.errorRed,
  fontSize: 14,
  fontWeight: 600,
  cursor: "pointer",
},
copyToast: {
  position: "fixed",
  bottom: "24px",
  right: "24px",
  backgroundColor: colors.white,
  color: colors.black,
  padding: "20px 24px",
  borderRadius: 16,
  boxShadow: "0 8px 24px rgba(0, 0, 0, 0.12)",
  display: "flex",
  alignItems: "center",
  gap: "12px",
  zIndex: 9999,
  minWidth: "320px",
},

copyToastIcon: {
  fontSize: 24,
  color: colors.black,
  flexShrink: 0,
},

copyToastText: {
  fontSize: 16,
  fontWeight: 500,
},

// Error-variant of the toast used for scan failures (bad image, AI error, etc.).
errorToast: {
  position: "fixed",
  bottom: "24px",
  right: "24px",
  backgroundColor: colors.errorRed,
  color: colors.white,
  padding: "20px 24px",
  borderRadius: 16,
  boxShadow: "0 8px 24px rgba(211, 47, 47, 0.32)",
  display: "flex",
  alignItems: "flex-start",
  gap: "12px",
  zIndex: 9999,
  minWidth: "320px",
  maxWidth: "420px",
},

errorToastIcon: {
  fontSize: 24,
  color: colors.white,
  flexShrink: 0,
  marginTop: 2,
},

errorToastText: {
  fontSize: 15,
  fontWeight: 500,
  lineHeight: 1.4,
},

scanResultsWrap: {
  width: "100%",
  maxWidth: 1400,
  margin: "0 auto",
},
scanResultsPanel: {
  background: colors.white,
  borderRadius: 16,
  border: `1px solid ${colors.bordwhite}`,
  padding: "16px 20px",
  boxShadow: "0 2px 8px rgba(0, 0, 0, 0.04)",
  maxHeight: "70vh",
  overflowY: "auto" as const,
},
scanResultsHeader: {
  display: "flex",
  alignItems: "flex-start",
  justifyContent: "space-between",
  gap: 12,
  marginBottom: 12,
  paddingBottom: 12,
  borderBottom: `1px solid ${colors.bordwhite}`,
},
scanResultsTitleWrap: {
  display: "flex",
  flexDirection: "column" as const,
  gap: 6,
  flex: 1,
  minWidth: 0,
},
scanResultsTitle: {
  display: "flex",
  alignItems: "center",
  gap: 8,
  fontSize: 16,
  fontWeight: 700,
  color: colors.darkTeal,
},
scanResultsSubtitle: {
  fontSize: 12,
  color: colors.grayText,
  marginLeft: 28,
},
scanResultsCountRow: {
  display: "flex",
  gap: 6,
  flexWrap: "wrap" as const,
  marginLeft: 28,
  marginTop: 2,
},
scanResultsCountBadge: {
  fontSize: 11,
  fontWeight: 700,
  padding: "3px 8px",
  borderRadius: 999,
  textTransform: "uppercase" as const,
  letterSpacing: 0.3,
},
scanResultsCountBadgeAdded: {
  background: colors.lightTeal,
  color: colors.darkTeal,
},
scanResultsCountBadgeUpdated: {
  background: colors.warningYellowBg,
  color: colors.warningYellowText,
},
scanResultsCountBadgeRemoved: {
  background: "rgba(211, 47, 47, 0.1)",
  color: colors.errorRed,
},
scanResultsClose: {
  background: "none",
  border: "none",
  cursor: "pointer",
  padding: 4,
  color: colors.grayText,
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  borderRadius: 6,
  flexShrink: 0,
},
scanResultsEmpty: {
  fontSize: 14,
  color: colors.grayText,
  margin: 0,
  padding: "16px 0 4px",
  textAlign: "center" as const,
  fontStyle: "italic" as const,
},
scanResultsGrid: {
  display: "grid",
  gridTemplateColumns: "repeat(auto-fit, minmax(360px, 1fr))",
  gap: 12,
  alignItems: "start" as const,
},
changeSection: {
  borderRadius: 12,
  padding: "12px 12px 10px",
  display: "flex",
  flexDirection: "column" as const,
  minWidth: 0,
},
changeSectionAdded: {
  background: colors.lightTeal,
},
changeSectionUpdated: {
  background: colors.warningYellowBg,
},
changeSectionRemoved: {
  background: "rgba(211, 47, 47, 0.08)",
},
changeSectionHeader: {
  display: "flex",
  alignItems: "center",
  gap: 8,
  fontSize: 13,
  fontWeight: 700,
  marginBottom: 10,
  textTransform: "uppercase" as const,
  letterSpacing: 0.4,
},
changeSectionHeaderAdded: {
  color: colors.darkTeal,
},
changeSectionHeaderUpdated: {
  color: colors.warningYellowText,
},
changeSectionHeaderRemoved: {
  color: colors.errorRed,
},
chipContainer: {
  display: "flex",
  flexWrap: "wrap" as const,
  gap: 6,
  maxHeight: 260,
  overflowY: "auto" as const,
  paddingRight: 2,
},
chip: {
  display: "inline-flex",
  alignItems: "baseline",
  gap: 6,
  background: colors.white,
  borderRadius: 999,
  padding: "5px 12px",
  fontSize: 13,
  lineHeight: 1.3,
  maxWidth: "100%",
  boxShadow: "0 1px 2px rgba(0, 0, 0, 0.04)",
},
chipName: {
  fontWeight: 600,
  color: colors.black,
  textTransform: "capitalize" as const,
  whiteSpace: "nowrap" as const,
  overflow: "hidden" as const,
  textOverflow: "ellipsis" as const,
  maxWidth: 140,
},
chipQty: {
  color: colors.grayText,
  fontSize: 12,
  whiteSpace: "nowrap" as const,
},
chipQtyStrike: {
  color: colors.grayText,
  fontSize: 12,
  textDecoration: "line-through" as const,
  whiteSpace: "nowrap" as const,
},
chipArrow: {
  color: colors.grayText,
  fontSize: 12,
},
createBtn: {
  width: "60%",
  padding: "10px",
  margin: "24px auto 0 auto",
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  gap: "10px",
  borderRadius: 12,
  background: colors.accentGreen,
  color: colors.white,
  fontSize: 16,
  fontWeight: 600,
  cursor: "pointer",
},
joinBtn: {
  width: "60%",
  padding: "10px",
  margin: "24px auto 0 auto",
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  gap: "10px",
  borderRadius: 12,
  border: `2px solid ${colors.accentGreen}`,
  background: colors.white,
  color: colors.accentGreen,
  fontSize: 16,
  fontWeight: 600,
  cursor: "pointer",
},
input: {
  width: "60%",
  padding: "10px",
  margin: "16px auto 0 auto",
    display: "flex",
  justifyContent: "center",
  alignItems: "center",
  gap: "10px",
  border: "1px solid #ccc",
  borderRadius: "10px",
  fontSize: "14px",
  backgroundColor: "colors.white",
  boxSizing: "border-box",
  marginBottom: "12px",
},
imageWrapper: {
  position: 'relative' as const,
},
imagePreview: {
  width: 80,
  height: 80,
  borderRadius: 8,
  objectFit: 'cover' as const,
},
imageDeleteBtn: {
  position: 'absolute' as const,
  top: -6,
  right: -6,
  width: 20,
  height: 20,
  borderRadius: '50%',
  background: colors.white,
  color: colors.black,
  border: '1px solid #e0e0e0',
  cursor: 'pointer',
  fontSize: 12,
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
},
imagesContainer: {
  display: 'flex',
  gap: 8,
  marginTop: 12,
  flexWrap: 'wrap' as const,
  alignItems: 'center',
  justifyContent: 'center',
},
sendScanBtn: {
  width: 50,
  height: 50,
  borderRadius: '50%',
  background: colors.accentGreen,
  color: colors.white,
  border: 'none',
  cursor: 'pointer',
  fontSize: 28,
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
},
spinner: {
  width: 40,
  height: 40,
  borderRadius: '50%',
  border: '4px solid #e0e0e0',
  borderTop: `4px solid ${colors.darkTeal}`,
  animation: 'spin 1s linear infinite',
},
spinnerWrapper: {
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  height: '100vh',
},
memberAvatarImg: {
  width: '100%',
  height: '100%',
  borderRadius: '50%',
  objectFit: 'cover' as const,
},
};

export const iconProps = {
  backIcon: {
    size: 24,
    color: colors.grayText,
  },
  peopleIcon: {
    size: 18,
    color: colors.accentGreen,
  },
  cameraIcon: {
    size: 18,
    color: colors.accentGreen,
  },
  uploadIcon: {
    size: 18,
    color: colors.white,
  },
  copyIcon: {
    size: 13,
    color: colors.white,
  },
  leaveIcon: {
    size: 15,
    color: colors.errorRed,
  },
  fridgeOffIcon: {
    size: 20,
    color: colors.black,
  },
  sendIcon: {
  size: 24,
  color: colors.white,
},
closeIcon: {
  size: 12,
  color: colors.black,
},
scanResultsCloseIcon: {
  size: 18,
  color: colors.grayText,
},
scanResultsTitleIcon: {
  size: 20,
  color: colors.accentGreen,
},
scanAddedIcon: {
  size: 16,
  color: colors.accentGreen,
},
scanUpdatedIcon: {
  size: 16,
  color: colors.warningYellowText,
},
scanRemovedIcon: {
  size: 16,
  color: colors.errorRed,
},
dropZoneIcon: {
  size: 26,
  color: colors.accentGreen,
},

};